<?php

/**
 * This is the model base class for the table "user_activity".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UserActivity".
 *
 * Columns in table "user_activity" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property integer $activity_id
 * @property integer $user_id
 * @property string $created_at
 * @property string $updated_at
 * @property string $status
 *
 */
abstract class BaseUserActivity extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'user_activity';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'UserActivity|UserActivities', $n);
	}

	public static function representingColumn() {
		return 'created_at';
	}

	public function rules() {
		return array(
			array('activity_id, user_id, created_at', 'required'),
			array('activity_id, user_id', 'numerical', 'integerOnly'=>true),
			array('status', 'length', 'max'=>1),
			array('updated_at', 'safe'),
			array('updated_at, status', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, activity_id, user_id, created_at, updated_at, status', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'activity_id' => Yii::t('app', 'Activity'),
			'user_id' => Yii::t('app', 'User'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'status' => Yii::t('app', 'Status'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('activity_id', $this->activity_id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);
		$criteria->compare('status', $this->status, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}