<?php

/**
 * This is the model base class for the table "ratings".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Ratings".
 *
 * Columns in table "ratings" available as properties of the model,
 * followed by relations of table "ratings" available as properties of the model.
 *
 * @property integer $rating_id
 * @property integer $campaign_id
 * @property integer $from_user_id
 * @property integer $to_user_id
 * @property double $ratings
 * @property integer $is_delete
 *
 * @property Campaign $campaign
 * @property UserDetail $fromUser
 * @property UserDetail $toUser
 */
abstract class BaseRatings extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'ratings';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Ratings|Ratings', $n);
	}

	public static function representingColumn() {
		return 'rating_id';
	}

	public function rules() {
		return array(
			array('campaign_id, from_user_id, to_user_id, ratings', 'required'),
			array('campaign_id, from_user_id, to_user_id, is_delete', 'numerical', 'integerOnly'=>true),
			array('ratings', 'numerical'),
			array('is_delete', 'default', 'setOnEmpty' => true, 'value' => null),
			array('rating_id, campaign_id, from_user_id, to_user_id, ratings, is_delete', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'campaign' => array(self::BELONGS_TO, 'Campaign', 'campaign_id'),
			'fromUser' => array(self::BELONGS_TO, 'UserDetail', 'from_user_id'),
			'toUser' => array(self::BELONGS_TO, 'UserDetail', 'to_user_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'rating_id' => Yii::t('app', 'Rating'),
			'campaign_id' => null,
			'from_user_id' => null,
			'to_user_id' => null,
			'ratings' => Yii::t('app', 'Ratings'),
			'is_delete' => Yii::t('app', 'Is Delete'),
			'campaign' => null,
			'fromUser' => null,
			'toUser' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('rating_id', $this->rating_id);
		$criteria->compare('campaign_id', $this->campaign_id);
		$criteria->compare('from_user_id', $this->from_user_id);
		$criteria->compare('to_user_id', $this->to_user_id);
		$criteria->compare('ratings', $this->ratings);
		$criteria->compare('is_delete', $this->is_delete);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}