<?php

/**
 * This is the model base class for the table "post_to_exchange_price".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PostToExchangePrice".
 *
 * Columns in table "post_to_exchange_price" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $price_id
 * @property integer $no_days
 * @property double $price
 * @property integer $status
 *
 */
abstract class BasePostToExchangePrice extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'post_to_exchange_price';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'PostToExchangePrice|PostToExchangePrices', $n);
	}

	public static function representingColumn() {
		return 'price_id';
	}

	public function rules() {
		return array(
			array('no_days, price, status', 'required'),
			array('no_days, status', 'numerical', 'integerOnly'=>true),
			array('price', 'numerical'),
			array('price_id, no_days, price, status', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'price_id' => Yii::t('app', 'Price'),
			'no_days' => Yii::t('app', 'No Days'),
			'price' => Yii::t('app', 'Price'),
			'status' => Yii::t('app', 'Status'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('price_id', $this->price_id);
		$criteria->compare('no_days', $this->no_days);
		$criteria->compare('price', $this->price);
		$criteria->compare('status', $this->status);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}