<?php

/**
 * This is the model base class for the table "entourage_notification".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "EntourageNotification".
 *
 * Columns in table "entourage_notification" available as properties of the model,
 * followed by relations of table "entourage_notification" available as properties of the model.
 *
 * @property integer $entourage_id
 * @property integer $user_id
 * @property string $screen_name
 * @property integer $new_entourage
 * @property integer $post_to_exchange
 * @property integer $badge
 *
 * @property UserDetail $user
 */
abstract class BaseEntourageNotification extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'entourage_notification';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'EntourageNotification|EntourageNotifications', $n);
	}

	public static function representingColumn() {
		return 'screen_name';
	}

	public function rules() {
		return array(
			array('user_id, screen_name', 'required'),
			array('user_id, new_entourage, post_to_exchange, badge', 'numerical', 'integerOnly'=>true),
			array('screen_name', 'length', 'max'=>100),
			array('new_entourage, post_to_exchange, badge', 'default', 'setOnEmpty' => true, 'value' => null),
			array('entourage_id, user_id, screen_name, new_entourage, post_to_exchange, badge', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'user' => array(self::BELONGS_TO, 'UserDetail', 'user_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'entourage_id' => Yii::t('app', 'Entourage'),
			'user_id' => null,
			'screen_name' => Yii::t('app', 'Screen Name'),
			'new_entourage' => Yii::t('app', 'New Entourage'),
			'post_to_exchange' => Yii::t('app', 'Post To Exchange'),
			'badge' => Yii::t('app', 'Badge'),
			'user' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('entourage_id', $this->entourage_id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('screen_name', $this->screen_name, true);
		$criteria->compare('new_entourage', $this->new_entourage);
		$criteria->compare('post_to_exchange', $this->post_to_exchange);
		$criteria->compare('badge', $this->badge);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}