<?php

/**
 * This is the model base class for the table "activity_list".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ActivityList".
 *
 * Columns in table "activity_list" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $activity_id
 * @property string $activity_name
 * @property string $created_at
 * @property string $updated_at
 * @property string $status
 *
 */
abstract class BaseActivityList extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'activity_list';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ActivityList|ActivityLists', $n);
	}

	public static function representingColumn() {
		return 'activity_name';
	}

	public function rules() {
		return array(
			array('activity_name, created_at', 'required'),
			array('activity_name', 'length', 'max'=>500),
			array('status', 'length', 'max'=>1),
			array('updated_at', 'safe'),
			array('updated_at, status', 'default', 'setOnEmpty' => true, 'value' => null),
			array('activity_id, activity_name, created_at, updated_at, status', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'activity_id' => Yii::t('app', 'Activity'),
			'activity_name' => Yii::t('app', 'Activity Name'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'status' => Yii::t('app', 'Status'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('activity_id', $this->activity_id, true);
		$criteria->compare('activity_name', $this->activity_name, true);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);
		$criteria->compare('status', $this->status, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}