<?php

/**
 * This is the model base class for the table "campaign_partner".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CampaignPartner".
 *
 * Columns in table "campaign_partner" available as properties of the model,
 * followed by relations of table "campaign_partner" available as properties of the model.
 *
 * @property integer $id
 * @property integer $campaign_id
 * @property string $twitter_screen_name
 * @property integer $is_member
 * @property integer $is_verified
 * @property double $impact_score
 * @property double $price
 * @property integer $reach
 * @property string $fb_post_id
 * @property string $twitter_post_id
 * @property string $fb_reach
 * @property string $twitter_reach
 * @property integer $is_delete
 *
 * @property Campaign $campaign
 */
abstract class BaseCampaignPartner extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'campaign_partner';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'CampaignPartner|CampaignPartners', $n);
	}

	public static function representingColumn() {
		return 'twitter_screen_name';
	}

	public function rules() {
		return array(
			array('campaign_id, twitter_screen_name, is_member, is_verified, impact_score, price, reach, fb_post_id, twitter_post_id, fb_reach, twitter_reach', 'required'),
			array('campaign_id, is_member, is_verified, reach, is_delete', 'numerical', 'integerOnly'=>true),
			array('impact_score, price', 'numerical'),
			array('twitter_screen_name', 'length', 'max'=>100),
			array('fb_post_id, twitter_post_id', 'length', 'max'=>250),
			array('fb_reach, twitter_reach', 'length', 'max'=>15),
			array('is_delete', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, campaign_id, twitter_screen_name, is_member, is_verified, impact_score, price, reach, fb_post_id, twitter_post_id, fb_reach, twitter_reach, is_delete', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'campaign' => array(self::BELONGS_TO, 'Campaign', 'campaign_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'campaign_id' => null,
			'twitter_screen_name' => Yii::t('app', 'Twitter Screen Name'),
			'is_member' => Yii::t('app', 'Is Member'),
			'is_verified' => Yii::t('app', 'Is Verified'),
			'impact_score' => Yii::t('app', 'Impact Score'),
			'price' => Yii::t('app', 'Price'),
			'reach' => Yii::t('app', 'Reach'),
			'fb_post_id' => Yii::t('app', 'Fb Post'),
			'twitter_post_id' => Yii::t('app', 'Twitter Post'),
			'fb_reach' => Yii::t('app', 'Fb Reach'),
			'twitter_reach' => Yii::t('app', 'Twitter Reach'),
			'is_delete' => Yii::t('app', 'Is Delete'),
			'campaign' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('campaign_id', $this->campaign_id);
		$criteria->compare('twitter_screen_name', $this->twitter_screen_name, true);
		$criteria->compare('is_member', $this->is_member);
		$criteria->compare('is_verified', $this->is_verified);
		$criteria->compare('impact_score', $this->impact_score);
		$criteria->compare('price', $this->price);
		$criteria->compare('reach', $this->reach);
		$criteria->compare('fb_post_id', $this->fb_post_id, true);
		$criteria->compare('twitter_post_id', $this->twitter_post_id, true);
		$criteria->compare('fb_reach', $this->fb_reach, true);
		$criteria->compare('twitter_reach', $this->twitter_reach, true);
		$criteria->compare('is_delete', $this->is_delete);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}